### ISSUE TITLE
Replicate Kotlin/Spring Boot example of TopicRecordNameStrategy with Go and gokfk-regent.

### ISSUE THREAD

**Issue by manuelarte** [djedjethai/gokfk-regent#8]
Hello,

First of all thanks for your library, I have the following example of multiple avro schemas for one kafka topic made with Kotlin/Spring Boot: https://github.com/manuelarte/kafka-kotlin-multiple-schemas-one-topic

I would like to replicate the same scenario in Go. For that I am using this library, the thing is that, when I try to register my schema, in my Kotlin app, using **TopicRecordNameStrategy**, I can register it like this `quickstart-events-com.github.manuelarte.kafka.avro.UserNew`, but using your library it adds a `-value` at the end `quickstart-events-com.github.manuelarte.kafka.avro.UserNew-value`.

I am guessing it's related to the fact that at the end `GetID` in `BaseSerializer` calls to `serde.TopicNameStrategy`:

PS: I have the Go project in a private repository, let me know if you want to check the code and I make it public

**Comment by djedjethai** [comment]
Hello,

The `-value` (or `-key`) suffix is due to the Subject Naming Convention used by Confluent. This convention adds `-value` for schemas representing values and `-key` for schemas representing keys. This approach allows schemas to be stored for both keys and values. For more details, refer to this short video [https://developer.confluent.io/courses/schema-registry/schema-subjects/](url)
(Note that this functionality is part of the official Confluent-kafka-go's SchemaRegistry)

In your code, it is defined as follows:
`serializer, err := avro.NewGenericSerializer(c, serde.ValueSerde, avro.NewSerializerConfig()) // avro generic`

If you want to register a schema for a key instead, the code would look like this:
`serializer, err := avro.NewGenericSerializer(c, serde.KeySerde, avro.NewSerializerConfig()) `

This behavior is handled by the function defined at `serde/serde.go` on line 136:
`func TopicNameStrategy(topic string, serdeType Type, fullyQualifiedName ...string) (string, error)`

When using this library to register and retrieve schemas, the naming convention is applied automatically, you simply define `serde.ValueSerde` or `serde.KeySerde` in the serializer, and there’s no need to worry about it. However, if you use a Kotlin client that does not append the `-value` or `-key` suffix on one side and this Go client on the other, you will encounter issues. To resolve this, you can either fork the project and modify the code (removing the `-key` or `-value` suffix) or manually append the `-value` or `-key` suffix to your schema name in the Kotlin client.

Hope this helps

**Comment by manuelarte** [comment]
Yes, I checked the library and I think I know how it works, but there is a
mismatch in the implementation and the link you sent to me, if you look at
topicrecordname subject strategy, you can see the following :

```
TopicRecordNameStrategy is a combination of the first two strategies.

Subject names are created using <topic name>-<fully qualified record name>.
```


As you can see, there is no suffix for _-key_, or _-value_.

This is the behaviour I see when using this strategy in java, for example, so that's why I think your implementation is wrong.

And that's what I want to address

**Comment by djedjethai** [comment]
The video shows that the naming convention also applies to the
TopicRecordNameStrategy, as illustrated in the attached picture.

**Comment by djedjethai** [comment]
The video shows that the naming convention also applies to the TopicRecordNameStrategy, as illustrated in the attached picture.![Screenshot_20241120_144247_Chrome.jpg](https://github.com/user-attachments/assets/7b1300da-7158-440f-8c90-f68e5a02f149)

**Comment by manuelarte** [comment]
Ok, that's weird because as you could read in the text they don't mention any suffix for TopicRecordName, and if I use this subject strategy using the confluent java library it does not add the suffix neither.

Apart from the fact that I can also see this
![Screenshot_20241120-092519.png](https://github.com/user-attachments/assets/df45ee2c-e672-4bc1-84a8-756cc0e55288)

https://developer.confluent.io/courses/schema-registry/schema-subjects/

**Comment by manuelarte** [comment]
But anyway, I'm not trying to convince you, if you think this is incorrect no problem.

**Comment by djedjethai** [comment]
The page your picture refer to does not specify the suffix either for the TopicNameStrategy, see below.

My point is, why would the first two strategies be able to store schemas for keys and values, while TopicRecordName would not? That doesn't make much sense. It's also strange that the Confluent Java library does not implement it. However, they seem to not prioritize schema registry clients as they only implement the TopicNameStrategy on the Go client and ignore the PR I submited. So this feature may miss in their Java client as well.

The only way to be sure is to ask them.![Screenshot_20241120_161407_Chrome.jpg](https://github.com/user-attachments/assets/d2fc8dd6-9358-4900-a838-29a3cb7249d5)

**Comment by manuelarte** [comment]
You are right, the best way is to ask them

 (but btw, if I look at the picture you attach I can see the suffix -value, topicA-value, topicB-value), and also in the text:
 
 ```
 TopicNameStrategy is the default setting. If auto.register.schema is set to true, schemas that are automatically registered by producers will be registered under topic-name-(key or value).

When you register a schema in any of the three ways previously mentioned, you provide the topic name appended with key or value, e.g. topicA-value.
```

And the feature of having TopicRecordName strategy is definitely not missing in the Java client, I linked in a previous comment a demo of an app using it.

But anyway, let's park the discussion because we see the documentation differently I guess.

Thanks for the library anyway
